version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...

      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Building the Docker images...

      - docker build -t auth -f ./apps/auth/Dockerfile .
      - docker tag auth:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/sleepr-auth

      - docker build -t payments -f ./apps/payments/Dockerfile .
      - docker tag payments:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/sleepr-payments

      - docker build -t reservations -f ./apps/reservations/Dockerfile .
      - docker tag reservations:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/sleepr-reservations

  post_build:
    commands:
      - echo Pushing the Docker images to Amazon ECR...

      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/sleepr-auth
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/sleepr-payments
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/sleepr-reservations
