services:
  reservations:
    build:
      context: .
      dockerfile: apps/reservations/Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    command: yarn start:dev reservations
    env_file:
      - apps/reservations/.env
    depends_on:
      - mysql

  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    ports:
      - '3001:3001'
    command: yarn start:dev auth
    env_file:
      - apps/auth/.env
    depends_on:
      - mysql

  payments:
    build:
      context: .
      dockerfile: apps/payments/Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    ports:
      - '3002:3002'
    command: yarn start:dev payments
    env_file:
      - apps/payments/.env
    depends_on:
      - mysql

  mysql:
    image: mysql
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
