apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - image: 805102730154.dkr.ecr.eu-north-1.amazonaws.com/sleepr/auth:latest
          name: auth
          env:
            - name: HTTP_PORT
              value: '3001'
            - name: AUTH_GRPC_URL
              value: '0.0.0.0:50051'
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-url
                  key: databaseUrl
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwtSecret
            - name: JWT_EXPIRY
              value: '3600s'
          ports:
            - containerPort: 3001
            - containerPort: 50051
