apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
  name: gateway
spec:
  ports:
    - name: gateway-http
      port: 3003
      protocol: TCP
      targetPort: 3003
  selector:
    app: gateway
  type: NodePort
