syntax = "proto3";
package auth;

service AuthService {
  rpc authenticate (Authentication) returns (User);
  rpc login (LoginRequest) returns (LoginResponse);
  rpc refresh (RefreshRequest) returns (LoginResponse);
  rpc logout (RefreshRequest) returns (LogoutResponse);
  rpc createUser (CreateUserRequest) returns (User);
  rpc deleteUser (DeleteUserRequest) returns (User);
}

message Authentication {
  string token = 1;
}

message LoginRequest {
  string email = 1;
  string password = 2;
}

message LoginResponse {
  string token = 1;
  string refresh_token = 2;
}

message RefreshRequest {
  string refresh_token = 1;
}

message LogoutResponse {
  bool success = 1;
}

message CreateUserRequest {
  string email = 1;
  string password = 2;
}

message DeleteUserRequest {
  string user_id = 1;
}

message User {
    string id = 1;
    string email = 2;
    string created_at = 3;
    string updated_at = 4;
    repeated string roles = 5;

    reserved 6;
    reserved "reservations";
}