// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.1
// source: auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';
import { Reservation } from './reservation';

export const protobufPackage = 'auth';

export interface Authentication {
  token: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface LoginResponse {
  token: string;
  refreshToken: string;
}

export interface RefreshRequest {
  refreshToken: string;
}

export interface LogoutResponse {
  success: boolean;
}

export interface CreateUserRequest {
  email: string;
  password: string;
}

export interface DeleteUserRequest {
  userId: string;
}

export interface User {
  id: string;
  email: string;
  createdAt: string;
  updatedAt: string;
  roles: string[];
  reservations: Reservation[];
}

export const AUTH_PACKAGE_NAME = 'auth';

export interface AuthServiceClient {
  authenticate(request: Authentication): Observable<User>;

  login(request: LoginRequest): Observable<LoginResponse>;

  refresh(request: RefreshRequest): Observable<LoginResponse>;

  logout(request: RefreshRequest): Observable<LogoutResponse>;

  createUser(request: CreateUserRequest): Observable<User>;

  deleteUser(request: DeleteUserRequest): Observable<User>;
}

export interface AuthServiceController {
  authenticate(
    request: Authentication,
  ): Promise<User> | Observable<User> | User;

  login(
    request: LoginRequest,
  ): Promise<LoginResponse> | Observable<LoginResponse> | LoginResponse;

  refresh(
    request: RefreshRequest,
  ): Promise<LoginResponse> | Observable<LoginResponse> | LoginResponse;

  logout(
    request: RefreshRequest,
  ): Promise<LogoutResponse> | Observable<LogoutResponse> | LogoutResponse;

  createUser(
    request: CreateUserRequest,
  ): Promise<User> | Observable<User> | User;

  deleteUser(
    request: DeleteUserRequest,
  ): Promise<User> | Observable<User> | User;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'authenticate',
      'login',
      'refresh',
      'logout',
      'createUser',
      'deleteUser',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('AuthService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('AuthService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const AUTH_SERVICE_NAME = 'AuthService';
