// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.1
// source: payments.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'payments';

export enum PaymentStatus {
  PAYMENT_STATUS_UNSPECIFIED = 0,
  PENDING = 1,
  SUCCEEDED = 2,
  FAILED = 3,
  CANCELLED = 4,
  UNRECOGNIZED = -1,
}

export interface Payment {
  id: string;
  reservationId: string;
  amount: number;
  status: PaymentStatus;
  createdAt: string;
  stripePaymentIntentId: string;
}

export interface CreatePaymentRequest {
  reservationId: string;
  amount: number;
  email: string;
  currency: string;
}

export interface CreatePaymentResponse {
  clientSecret: string;
  payment: Payment | undefined;
}

export interface ConfirmPaymentRequest {
  paymentIntentId: string;
  paymentMethodId: string;
}

export const PAYMENTS_PACKAGE_NAME = 'payments';

export interface PaymentsServiceClient {
  createPayment(
    request: CreatePaymentRequest,
  ): Observable<CreatePaymentResponse>;

  confirmPayment(request: ConfirmPaymentRequest): Observable<Payment>;
}

export interface PaymentsServiceController {
  createPayment(
    request: CreatePaymentRequest,
  ):
    | Promise<CreatePaymentResponse>
    | Observable<CreatePaymentResponse>
    | CreatePaymentResponse;

  confirmPayment(
    request: ConfirmPaymentRequest,
  ): Promise<Payment> | Observable<Payment> | Payment;
}

export function PaymentsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['createPayment', 'confirmPayment'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('PaymentsService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('PaymentsService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const PAYMENTS_SERVICE_NAME = 'PaymentsService';
