// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.1
// source: reservation.proto

/* eslint-disable */

export const protobufPackage = "reservations";

export enum ReservationStatus {
  RESERVATION_STATUS_UNSPECIFIED = 0,
  PENDING = 1,
  CONFIRMED = 2,
  CANCELLED = 3,
  COMPLETED = 4,
  UNRECOGNIZED = -1,
}

export interface Reservation {
  id: string;
  startDate: string;
  endDate: string;
  userId: string;
  placeId: string;
  createdAt: string;
  updatedAt: string;
  status: ReservationStatus;
}

export const RESERVATIONS_PACKAGE_NAME = "reservations";
