// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.1
// source: reservation.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';
import { Empty } from './google/protobuf/empty';

export enum ReservationStatus {
  RESERVATION_STATUS_UNSPECIFIED = 0,
  PENDING = 1,
  CONFIRMED = 2,
  CANCELLED = 3,
  COMPLETED = 4,
  UNRECOGNIZED = -1,
}

export interface Reservation {
  id: string;
  startDate: string;
  endDate: string;
  userId: string;
  placeId: string;
  createdAt: string;
  updatedAt: string;
  status: ReservationStatus;
}

export interface CreateReservationRequest {
  startDate: string;
  endDate: string;
  placeId: string;
  userId: string;
}

export interface ReservationsList {
  reservations: Reservation[];
}

export interface FindOneReservationRequest {
  id: string;
}

export interface UpdateReservationRequest {
  id: string;
  startDate?: string | undefined;
  endDate?: string | undefined;
  placeId?: string | undefined;
}

export interface RemoveReservationRequest {
  id: string;
}

export const RESERVATIONS_PACKAGE_NAME = 'reservations';

export interface ReservationServiceClient {
  create(request: CreateReservationRequest): Observable<Reservation>;

  findAll(request: Empty): Observable<ReservationsList>;

  findOne(request: FindOneReservationRequest): Observable<Reservation>;

  update(request: UpdateReservationRequest): Observable<Reservation>;

  remove(request: RemoveReservationRequest): Observable<Reservation>;
}

export interface ReservationServiceController {
  create(
    request: CreateReservationRequest,
  ): Promise<Reservation> | Observable<Reservation> | Reservation;

  findAll(
    request: Empty,
  ):
    | Promise<ReservationsList>
    | Observable<ReservationsList>
    | ReservationsList;

  findOne(
    request: FindOneReservationRequest,
  ): Promise<Reservation> | Observable<Reservation> | Reservation;

  update(
    request: UpdateReservationRequest,
  ): Promise<Reservation> | Observable<Reservation> | Reservation;

  remove(
    request: RemoveReservationRequest,
  ): Promise<Reservation> | Observable<Reservation> | Reservation;
}

export function ReservationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'create',
      'findAll',
      'findOne',
      'update',
      'remove',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('ReservationService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('ReservationService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const RESERVATION_SERVICE_NAME = 'ReservationService';
