apiVersion: v1
kind: Service
metadata:
  labels:
    app: reservations
  name: reservations-grpc
spec:
  ports:
    - name: reservations-grpc
      port: 50052
      protocol: TCP
      targetPort: 50052
  selector:
    app: reservations
  type: ClusterIP
